### ISSUE TITLE
Reduce code duplication in ContactFactory

### ISSUE THREAD

**Issue by DivineOmega** [rapidwebltd/php-google-contacts-v3-api#1]
There are several instances of code duplication in the ContactFactory. Some of these can be moved into private method(s) and called appropriately.

**Comment by luanrm** [comment]
Hi , thank you for the great api , but the test.php file does not work , I get this error: `Undefined variable: contactsArray in /var/www/html/google-contacts/vendor/rapidwebltd/php-google-contacts-v3-api/factories/ContactFactory.php on line 70`,
 you know what can be ?

**Comment by DivineOmega** [comment]
I'm closing this due to our new [PHP Google People API](https://github.com/rapidwebltd/php-google-people-api) package being a suitable replacement.
