### ISSUE TITLE
Class 'rapidweb\googlecontacts\helpers\GoogleHelper' not found

### ISSUE THREAD

**Issue by aaronlague** [rapidwebltd/php-google-contacts-v3-api#11]
I am getting this error when i visit the authorise-application.php page

**Comment by DivineOmega** [comment]
Have you installed the library via `composer`?

**Comment by m0rph03nix** [comment]
Hello, thank you for your work. I can't install composer as I don't have a ssh access (only ftp). Is there a way to get the dependencies (or other solution to make it work) ? Thank you.

**Comment by DivineOmega** [comment]
Hello @m0rph03nix. Could you install and run composer on your local machine and then upload the resulting files?

**Comment by DivineOmega** [comment]
Have you managed to get this resolved?

**Comment by m0rph03nix** [comment]
Hello @DivineOmega . Thank you for your tip! It works well ! 👍

**Comment by DivineOmega** [comment]
My pleasure.

I shall close this issues for now. If yourself or the original poster have any further problems, feel free to create a new issue.
