### ISSUE TITLE
composer required?

### ISSUE THREAD

**Issue by jayhapunkt** [rapidwebltd/php-google-contacts-v3-api#13]
Hi,

sorry i am new to php. 
I am not hosting on my own (buh... i know), and use a hosting service with a contact form.
Out of that, i want to create a Google contact with the data provided from the form.

However, i am not allowed to install composer on my hosting service (1blu).
Is there any workaround?

**Comment by DivineOmega** [comment]
If you download the code as a zip and extract it into your project, you should just be able to `require`/`include` all the files you need.

**Comment by DivineOmega** [comment]
Did you get this issue resolved at all?

**Comment by DivineOmega** [comment]
Closing due to lack of response.
