### ISSUE TITLE
test.php does not work

### ISSUE THREAD

**Issue by luanrm** [rapidwebltd/php-google-contacts-v3-api#14]
Hi , thank you for the great api , but the test.php file does not work , I get this error: `Undefined variable: contactsArray in /var/www/html/google-contacts/vendor/rapidwebltd/php-google-contacts-v3-api/factories/ContactFactory.php on line 70`,
you know what can be ?

**Comment by DivineOmega** [comment]
Just pushed a commit to master that should fix this. However, the fact you got this error suggests no contacts could be retrieved. After grabbing the new version, make sure to check all your configuration and authorisation.

**Comment by luanrm** [comment]
Thank you for your help, I followed all the configuration steps and filled the .config.json, the contacts did not come , but also did not show any errors, is there any way to know that I am logging correctly?

**Comment by luanrm** [comment]
thanks
