### ISSUE TITLE
Perhaps integrate multi-user support

### ISSUE THREAD

**Issue by DivineOmega** [rapidwebltd/php-google-contacts-v3-api#2]

**Comment by vsauerde** [comment]
I don't know what you exactly mean with "multi-user support". But attached you'll find a patch, that enables your library to be used with different google-accounts without touching .config.json.
It's done by supplying a json-object to GetAll().
This way, you can pull several google-accounts in just one script.


[multiuser.patch.txt](https://github.com/rapidwebltd/php-google-contacts-v3-api/files/177721/multiuser.patch.txt)

**Comment by DivineOmega** [comment]
This has been resolved by https://github.com/rapidwebltd/php-google-contacts-v3-api/pull/38.
