### ISSUE TITLE
It works with only one google account?

### ISSUE THREAD

**Issue by rudijuri** [rapidwebltd/php-google-contacts-v3-api#20]
Thanks for the work done.
We can use this software you just associating it with a specific Google account , or with all the user accounts that permit on google ?

Thanks in advance.
Sorry for my bad english.

**Comment by DivineOmega** [comment]
The library can be used with any Google account you wish. It can be used by multiple accounts now due to recent pull request https://github.com/rapidwebltd/php-google-contacts-v3-api/pull/38.
