### ISSUE TITLE
Overlap contacts of the same type

### ISSUE THREAD

**Issue by lucascdsilva** [rapidwebltd/php-google-contacts-v3-api#22]
So I understand the code, does not allow pulling contacts with the same type, since it uses the contact type as array key.

Ex:

| Type | Number |
| --- | --- |
| cell | 99999999 |
| cell | 88888888 |

```php 
   //result only 
   array('cell' => 88888888);
```

**Comment by DivineOmega** [comment]
Good spot!

**Comment by DivineOmega** [comment]
Fixed by PR #23.
