### ISSUE TITLE
Warning: rapidweb\googlecontacts\factories\ContactFactory::submitUpdates(): Cannot assign to an array of nodes (duplicate subnodes or attr detected)

### ISSUE THREAD

**Issue by cdkdang** [rapidwebltd/php-google-contacts-v3-api#24]
Not sure what I've done wrong
when using test_individual.php?selfURL=http....... 
where selfURL is retrieved from one of the contacts in test.php
i get the following error:
Warning: rapidweb\googlecontacts\factories\ContactFactory::submitUpdates(): Cannot assign to an array of nodes (duplicate subnodes or attr detected) in C:\wamp2\www\gcontacts\factories\ContactFactory.php on line 147

**Comment by DivineOmega** [comment]
Not seen this one before. Are you using v1.1?

**Comment by DivineOmega** [comment]
I might believe I know what the issue is. Does the contact you are testing with have mutliple name, phone number or email fields?

**Comment by cdkdang** [comment]
Yes that was the case.

I removed the second number from the test contact and no longer have the error.

Unfortunately my contacts generally have multiple phone numbers (home, mobile, business etc). Is there anyway it would support multiple phone numbers?

**Comment by DivineOmega** [comment]
It can't currently support changing multiple fields of the same type, but this is definitely something that should be added.

I'll have to investigate it.

**Comment by cdkdang** [comment]
Also my contact phone numbers tend to have a custom field name.
eg. name: Example Trading
     address: 26 Fake Road, Nowhere. Australia. 3026
     Home: 03 9300 0001 <-- first telephone field
     Mobile: 0430 000 002 <-- second telephone field
     HK Number: +852 9876 5432 <-- third telephone field
And up to 10 different numbers (most are only two or three but there is one in particular which has 8).

**Comment by cdkdang** [comment]
Ok thanks for considering it.

Wish I was technically competent to help out.

**Comment by DivineOmega** [comment]
More information & discussion about contacts with multiple phone numbers is available in #32. Further discussion about this issue should go there for now.
