### ISSUE TITLE
Is there a way to add image to contact?

### ISSUE THREAD

**Issue by roulendz** [rapidwebltd/php-google-contacts-v3-api#25]
I was wondering if there a way to attach image to user profile?
By providing url to image.

Thanks!

**Comment by DivineOmega** [comment]
Hello @roulendz.

This is not currently possible with this library, but it's a great idea for a new feature. It should be possible to implement in the next release.

Official documentation for contact photo management: https://developers.google.com/google-apps/contacts/v3/#contact_photo_management

**Comment by DivineOmega** [comment]
We probably won't be adding the ability to add an image to a contact into this package.

However, we've recently written a new package, [PHP Google People API](https://github.com/rapidwebltd/php-google-people-api), which is capable of setting contact images. Hopefully this will help.
