### ISSUE TITLE
Does the client support Extended Properties?

### ISSUE THREAD

**Issue by sjordan1975** [rapidwebltd/php-google-contacts-v3-api#30]
From the documentation:

> It is possible to set any additional contact- or contact group- related information as an extended property (arbitrary name - value pair) for a contact or contact group entry. Preserving key uniqueness is a responsibility of clients. Value of the extended property may be stored as a value (arbitrary string) or an XML blob (these are mutually exclusive; instead of a valid XML blob plain text can be used). Each contact may have at most ten (10) extended properties associated. Each of them should be reasonably small, that is it should not be a photo, ringtone etc.

See https://developers.google.com/google-apps/contacts/v3/reference?authuser=1#ProjectionsAndExtended

**Comment by DivineOmega** [comment]
No, unfortunately extended properties are not supported. You should consider using our recently released [PHP Google People API](https://github.com/rapidwebltd/php-google-people-api) package which might be able to help with this.
