### ISSUE TITLE
Installation with composer

### ISSUE THREAD

**Issue by MiguelVelazquez** [rapidwebltd/php-google-contacts-v3-api#34]
When runing composer update with the following code:
```json
{
  "require": {
       "rapidwebltd/php-google-contacts-v3-api": "1.*"
   }
}
```
I just see the files of the google api
Am I doing something wrong?
Is there a directory structure I should follow?

**Comment by MiguelVelazquez** [comment]
Turns out it was an error in sublime or something that didn't let me open de `rapidwebltd` folder.
It is fixed restarting sublime.

**Comment by DivineOmega** [comment]
Perhaps Sublime just didn't refresh the directory tree correctly. Glad it's sorted.
