### ISSUE TITLE
Fatal error: Class 'Google_Http_Request' not found

### ISSUE THREAD

**Issue by Dr34ml4and3r** [rapidwebltd/php-google-contacts-v3-api#35]
I encounter this error:
Fatal error: Class 'Google_Http_Request' not found in /factories/ContactFactory.php on line 
        $req = new \Google_Http_Request('https://www.google.com/m8/feeds/contacts/default/full?max-results=10000&updated-min=2007-03-16T00:00:00');

I installed manually the script, downloaded the code as a zip and extract it into my host.
I'm using the latest version of https://github.com/google/google-api-php-client
Please,Can you guide me to find out what is causing this error?Seems is missing some library/dependencies?
Thank you!

**Comment by Dr34ml4and3r** [comment]
I installed the script with composer and I saw that the script, in order to run properly,needs google/apiclient (v1.1.8), so I think the Google_Http_Request class is removed in the latest version of google-api-php-client.

**Comment by DivineOmega** [comment]
Hello.

You shouldn't be using the `master` branch as this used for development, so you will probably have issues. You should use the latest stable release (1.3 at time of writing). See here: https://github.com/rapidwebltd/php-google-contacts-v3-api/releases.

However, I would strongly advise installing using `composer` instead as this will ensure all required dependencies are automatically installed for you. The latest stable version of this library requires Google API Client 1.*.* and does not support version 2 or above.

Best regards

**Comment by DivineOmega** [comment]
Did you manage to get this issue resolved?

**Comment by Dr34ml4and3r** [comment]
Yes, I managed to resolve this issue,to run propely the script needs google/api_php_client v1.1.8
Thank you!
