### ISSUE TITLE
Add/update and delete contact images 

### ISSUE THREAD

**Issue by etetlow** [rapidwebltd/php-google-contacts-v3-api#40]
Hi. I did see that there was some talk of being able to add images to contacts a while back. Has there been any advancement on this and if so how far along are we? Just wondering because if nothing has been done, I'll take a fork and attempt it myself.

Thanks.

**Comment by DivineOmega** [comment]
Hi. There's not been any work regarding adding images to contacts.

Feel free to fork the project. We'd welcome the contribution.

Thanks.

**Comment by etetlow** [comment]
Thanks, will do. While I've got you here, has there been any work on extending into the gContact namespace? Some of those extra details would be very handy.

**Comment by DivineOmega** [comment]
Not really. This mostly just handles the basic details.

**Comment by DivineOmega** [comment]
See #25 for more details.
