### ISSUE TITLE
authorization link crashed

### ISSUE THREAD

**Issue by aa-ahmed-aa** [rapidwebltd/php-google-contacts-v3-api#49]
after i get the link after opening authorise-application.php in the browser ,i tried to authorize the app but the link won't open ,the link redirected me to a crashed site

**Comment by DivineOmega** [comment]
Hi @aa-ahmed-aa. Could you provide a screenshot of the 'crashed site' you are getting redirect to?

**Comment by aa-ahmed-aa** [comment]
i get this error in google site after redirecting 

> 400. That’s an error.
> 
> Error: invalid_request
> 
> Missing required parameter: redirect_uri
> 
> Learn more
> 
> Request Details
> response_type=code
> redirect_uri[0]=urn:ietf:wg:oauth:2.0:oob
> redirect_uri[1]=http://localhost
> client_id=191598484639-d69a0chvmh0kc7gsmlgan64f1s6opifl.apps.googleusercontent.com
> scope=https://www.google.com/m8/feeds/
> access_type=offline
> approval_prompt=force
> That’s all we know.

**Comment by DivineOmega** [comment]
You need to make sure the `redirectUri` in your `.config.json` is pointing towards the `redirect-handler.php` file.

**Comment by aa-ahmed-aa** [comment]
thanks @DivineOmega

**Comment by DivineOmega** [comment]
Glad I could help! :)
