### ISSUE TITLE
how to get selfURL ?

### ISSUE THREAD

**Issue by aa-ahmed-aa** [rapidwebltd/php-google-contacts-v3-api#50]
How to get the selfUrl of specific user to can update his data ?

**Comment by DivineOmega** [comment]
Each contact object contains a self URL. If you get all the contacts, as below, you will be able to see the self URL for each contact.

```php
$contacts = rapidweb\googlecontacts\factories\ContactFactory::getAll();

var_dump($contacts);
```

**Comment by aa-ahmed-aa** [comment]
Thanks Again  @DivineOmega
