### ISSUE TITLE
Delete contact from my account

### ISSUE THREAD

**Issue by aa-ahmed-aa** [rapidwebltd/php-google-contacts-v3-api#51]
i checked the readme and i didn't find anythhing mentioned ,so how can i delete contact from my account ?

**Comment by DivineOmega** [comment]
Although it is not yet documented, the `ContactFactory` has a delete method.

See here: https://github.com/rapidwebltd/php-google-contacts-v3-api/blob/master/factories/ContactFactory.php#L297

You should be able to pass a `Contact` object to this method to delete it.

**Comment by aa-ahmed-aa** [comment]
i get the contact by self url then pass it to the delete function and i get this error here is the code 
```php
$contact = ContactFactory::getBySelfURL($data['self_url']);
$deleted = ContactFactory::delete( $contact );
```
i get this error 
https://drive.google.com/drive/u/1/my-drive
