### ISSUE TITLE
Delete all contacts

### ISSUE THREAD

**Issue by gentianes** [rapidwebltd/php-google-contacts-v3-api#54]
Hello and thank you for your project,
Would it be possible to implement the delete function for all contacts?
That would be very helpful.
Thank you very much.

**Comment by DivineOmega** [comment]
You should be able to delete all contacts with something similar to the following.

```php
$contacts = ContactFactory::getAll();
foreach($contacts as $contact) {
  ContactFactory::delete($contact);
}
