### ISSUE TITLE
Can't access many attributes !

### ISSUE THREAD

**Issue by aa-ahmed-aa** [rapidwebltd/php-google-contacts-v3-api#55]
i want to access some attributes in the api but i can't do this
the create method can only set the name, email,phonenumber and notes, i want to set many other variables EXP: ['organization']['orgName'], i'll try to do this with my instance of the repo but i want to check if there is any tries have made before with this task ,and is it doable or not ?

**Comment by DivineOmega** [comment]
Unfortunately, this library can't access all extended attributes. 

It might be worth taking a look at a new package we've made, [PHP Google People API](https://github.com/rapidwebltd/php-google-people-api), which is far more capable.
