### ISSUE TITLE
Error 400 authorise-application.php generated link

### ISSUE THREAD

**Issue by lrcvrino** [rapidwebltd/php-google-contacts-v3-api#57]
When I follow the generated link give me that error.

![error400](https://user-images.githubusercontent.com/5780594/36645611-cd3aa31c-1a6b-11e8-9364-8d30017b35a2.png)

.config.json file:
`
{
    "clientID": "1038blabla05-fekamkh9blablablal2s9r9e2fj9a.apps.googleusercontent.com",
    "clientSecret": "QA-FiblablablaANYXnIH",
    "redirectUri": "redirect-handler.php",
    "developerKey": "",
    "refreshToken": ""
}
`
I tired in windows 10 with xampp and before into a raspberry pi 3 so i understand that I make some wrong.  Thanks.

**Comment by DivineOmega** [comment]
The `redirectUri` variable should be a full (publicly accessible) URL to the `redirect-handler.php`.

If you're not able to make the page publicly accessible, consider using our new [Google People API](https://github.com/rapidwebltd/php-google-people-api), which handles this authorization process much more elegantly, and lets you manipulate contacts much more easily.

**Comment by lrcvrino** [comment]
I feel so stupid! thanks. Of course I will use the new Google People API. Thansks so much

**Comment by DivineOmega** [comment]
Glad to help. :)
