### ISSUE TITLE
change google/apiclient dependencies to =1.1.6 as v2 break the code

### ISSUE THREAD

**Issue by devypt** [rapidwebltd/php-google-contacts-v3-api#6]
change google/apiclient dependencies to =1.1.6 as v2 break the code

**Comment by DivineOmega** [comment]
Thanks for the heads up. I wasn't aware of the new google/apiclient v2 release candidates.

**Comment by DivineOmega** [comment]
I've set the version number to `>=1.1.4 <2.0.0` which seems to do trick and allows for further v1.*.* versions.
