### ISSUE TITLE
How to obtain all emails and phoneNumbers from Google Contact?

### ISSUE THREAD

**Issue by j6soto** [rapidwebltd/php-google-contacts-v3-api#7]
I need to retrieve all emails and phoneNumbers from Google Contacts data. Do we have any plans to allow this? Currently in the ContactFactory.php it scans for email but seems to return only 1... looks like the last one of the Array.

Thanks for helping.!

**Comment by DivineOmega** [comment]
You're right. This would be a good addition.

When developing this initially I never came across a Google contact with more than one email and telephone number, but I know it is possible to add them. It shouldn't be too hard to add in.

**Comment by vsauerde** [comment]
I wrote a patch to obtain all emails and phoneNumbers.
They are returned as array in the rapidweb-contact-objekt.

`diff --git a/factories/ContactFactory.php b/factories/ContactFactory.php
index ffe9980..f603b52 100644
--- a/factories/ContactFactory.php
+++ b/factories/ContactFactory.php
@@ -39,15 +39,29 @@ abstract class ContactFactory
             }

             $contactGDNodes = $xmlContactsEntry->children('http://schemas.google.com/g/2005');
-
             foreach ($contactGDNodes as $key => $value) {
-                $attributes = $value->attributes();
-
-                if ($key == 'email') {
-                    $contactDetails[$key] = (string) $attributes['address'];
-                } else {
-                    $contactDetails[$key] = (string) $value;
-                }
+                               switch ($key) {
+                                       case 'organization':
+                                               $contactDetails[$key]['orgName'] = (string) $value->orgName;
+                                               $contactDetails[$key]['orgTitle'] = (string) $value->orgTitle;
+                                               break;
+                                       case 'email':
+                                               $attributes = $value->attributes();
+                                               $emailadress=(string)$attributes['address'];
+                                               $emailtype=substr(strstr($attributes['rel'],"#"),1);
+                                               $contactDetails[$key][$emailtype]=$emailadress;
+                                               break;
+                                       case 'phoneNumber':
+                                               $attributes = $value->attributes();
+                                               $uri=(string)$attributes['uri'];
+                                               $type=substr(strstr($attributes['rel'],"#"),1);
+                                               $e164=substr(strstr($uri,":"),1);
+                                               $contactDetails[$key][$type]=$e164;
+                                               break;
+                                       default:
+                                               $contactDetails[$key] = (string) $value;
+                                               break;
+`

**Comment by DivineOmega** [comment]
Thanks for the patch @vsauerde.

I've applied to it to master (https://github.com/rapidwebltd/php-google-contacts-v3-api/commit/04222a218d55132b94a3a7076ce4be124bc5e59e).

**Comment by DivineOmega** [comment]
@j6soto This should solve your issue. Would you be able to get this a test for us?

**Comment by Thord** [comment]
Is it possible to also get the group?

**Comment by DivineOmega** [comment]
I'm closing this issue now as the originally reported problem has been solved, and further improved for email addresses/phone numbers of the same type, via the recent PR #23.

@Thord If you still need to retrieve the contact group, please open a new issue detailing your requirements.

Many thanks all.
