### ISSUE TITLE
how to get/edit other user's contacts? [Support for Google domain service accounts]

### ISSUE THREAD

**Issue by eyalgett** [rapidwebltd/php-google-contacts-v3-api#8]
I'm trying to get/edit a user contact in my google domain account.
the script isn't able to do so.
is there anywhere in the config to set it to run as a service account or something?

**Comment by DivineOmega** [comment]
I'm don't think that is supported by this version of the Google's Contact API. For this client library, you have the authenticate with the user whose contacts you wish to update.

If you have a limited number of users, you could authenticate each user and store each user's config file, swapping them out when needed. What's your use case?

**Comment by eyalgett** [comment]
a 800 users google business account, doing it manually for each user won't work..
thing is, there are google apps on the marketplace that can push contacts to the users, so i wonder how do they do it?

**Comment by DivineOmega** [comment]
This might be functionality offered/exposed by Google's API Client version 2.x, although I've yet to look into it.

An issue (#9) is already open for support version 2 of Google's API Client.
